# Path to the SSL/TLS certificate file
#cert_path = "./cacert.pem"

# Network configurations
[networks]

# Example network configuration
[networks.alvaro-cond-tests-celo10]
sequencers = [
    "0",
    "1",
    "2",
]

# Blank network configuration
# [networks.alvaro-conductor-stack]
# sequencers = [
#     "a",
#     "b",
#     "c",
# ]

[networks.alfajores-cel2]
sequencers = [
    "a",
    "b",
    "c",
]

# Sequencer configurations
[sequencers]

# Example sequencer configuration for op-network-1 with three sequencers
[sequencers.0]
raft_addr = "http://localhost:8001/api/v1/namespaces/alvaro-cond-tests-celo10/services/op-conductor-consensus-0:consensus/proxy/"
conductor_rpc_url = "http://localhost:8001/api/v1/namespaces/alvaro-cond-tests-celo10/services/op-conductor-rpc-0:rpc/proxy/"
node_rpc_url = "http://localhost:8001/api/v1/namespaces/alvaro-cond-tests-celo10/services/op-node-sequencer-rpc-0:rpc/proxy/"
voting = true

[sequencers.1]
raft_addr = "http://localhost:8001/api/v1/namespaces/alvaro-cond-tests-celo10/services/op-conductor-consensus-1:consensus/proxy/"
conductor_rpc_url = "http://localhost:8001/api/v1/namespaces/alvaro-cond-tests-celo10/services/op-conductor-rpc-1:rpc/proxy/"
node_rpc_url = "http://localhost:8001/api/v1/namespaces/alvaro-cond-tests-celo10/services/op-node-sequencer-rpc-1:rpc/proxy/"
voting = true

[sequencers.2]
raft_addr = "http://localhost:8001/api/v1/namespaces/alvaro-cond-tests-celo10/services/op-conductor-consensus-2:consensus/proxy/"
conductor_rpc_url = "http://localhost:8001/api/v1/namespaces/alvaro-cond-tests-celo10/services/op-conductor-rpc-2:rpc/proxy/"
node_rpc_url = "http://localhost:8001/api/v1/namespaces/alvaro-cond-tests-celo10/services/op-node-sequencer-rpc-2:rpc/proxy/"
voting = true

# Blank sequencer configuration for op-network-N with three blank sequencers
#[sequencers.a]
#raft_addr = "http://localhost:8001/api/v1/namespaces/alvaro-conductor-stack/services/op-conductor-a-consensus-0:consensus/proxy/"
#conductor_rpc_url = "http://localhost:8001/api/v1/namespaces/alvaro-conductor-stack/services/op-conductor-a-rpc-0:rpc/proxy/"
#node_rpc_url = "http://localhost:8001/api/v1/namespaces/alvaro-conductor-stack/services/op-node-sequencer-a-rpc-0:rpc/proxy/"
#voting = true
#
#[sequencers.b]
#raft_addr = "http://localhost:8001/api/v1/namespaces/alvaro-conductor-stack/services/op-conductor-b-consensus-0:consensus/proxy/"
#conductor_rpc_url = "http://localhost:8001/api/v1/namespaces/alvaro-conductor-stack/services/op-conductor-b-rpc-0:rpc/proxy/"
#node_rpc_url = "http://localhost:8001/api/v1/namespaces/alvaro-conductor-stack/services/op-node-sequencer-b-rpc-0:rpc/proxy/"
#voting = true
#
#[sequencers.c]
#raft_addr = "http://localhost:8001/api/v1/namespaces/alvaro-conductor-stack/services/op-conductor-c-consensus-0:consensus/proxy/"
#conductor_rpc_url = "http://localhost:8001/api/v1/namespaces/alvaro-conductor-stack/services/op-conductor-c-rpc-0:rpc/proxy/"
#node_rpc_url = "http://localhost:8001/api/v1/namespaces/alvaro-conductor-stack/services/op-node-sequencer-c-rpc-0:rpc/proxy/"
#voting = true

[sequencers.a]
raft_addr = "http://localhost:8001/api/v1/namespaces/alfajores-cel2/services/op-conductor-consensus-0:consensus/proxy/"
conductor_rpc_url = "http://localhost:8001/api/v1/namespaces/alfajores-cel2/services/op-conductor-rpc-0:rpc/proxy/"
node_rpc_url = "http://localhost:8001/api/v1/namespaces/alfajores-cel2/services/op-node-sequencer-rpc-0:rpc/proxy/"
voting = true

[sequencers.b]
raft_addr = "http://localhost:8001/api/v1/namespaces/alfajores-cel2/services/op-conductor-b-consensus-0:consensus/proxy/"
conductor_rpc_url = "http://localhost:8001/api/v1/namespaces/alfajores-cel2/services/op-conductor-b-rpc-0:rpc/proxy/"
node_rpc_url = "http://localhost:8001/api/v1/namespaces/alfajores-cel2/services/op-node-sequencer-b-rpc-0:rpc/proxy/"
voting = true

[sequencers.c]
raft_addr = "http://localhost:8001/api/v1/namespaces/alfajores-cel2/services/op-conductor-c-consensus-0:consensus/proxy/"
conductor_rpc_url = "http://localhost:8001/api/v1/namespaces/alfajores-cel2/services/op-conductor-c-rpc-0:rpc/proxy/"
node_rpc_url = "http://localhost:8001/api/v1/namespaces/alfajores-cel2/services/op-node-sequencer-c-rpc-0:rpc/proxy/"
voting = true

