# Path to the SSL/TLS certificate file
#cert_path = "./cacert.pem"

# Network configurations
[networks]

[networks.alfajores-cel2]
sequencers = [
    "a",
    "b",
    "c",
]

# Sequencer configurations
[sequencers]

[sequencers.a]
raft_addr = "http://op-conductor-consensus-0:50050"
conductor_rpc_url = "http://op-conductor-rpc-0:8545"
node_rpc_url = "http://op-node-sequencer-rpc-0:9545"
voting = true

[sequencers.b]
raft_addr = "http://op-conductor-b-consensus-0:50050"
conductor_rpc_url = "http://op-conductor-b-rpc-0:8545"
node_rpc_url = "http://op-node-sequencer-b-rpc-0:9545"
voting = true

[sequencers.c]
raft_addr = "http://op-conductor-c-consensus-0:50050"
conductor_rpc_url = "http://op-conductor-c-rpc-0:8545"
node_rpc_url = "http://op-node-sequencer-c-rpc-0:9545"
voting = true
